config/routes.rb
Myapp::Application.routes.draw do
  resources :pi_settings

  resources :albums do
    resources :photos
  end

  root :to => 'visitors#new'
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
  end

  # GET /albums/new
  def new
    @album = Album.new
  end

  # GET /albums/1/edit
  def edit
  end

  # GET /albums/1/photos
  def photos
    @album = Album.find(params[:id])
  end

  # POST /albums
  # POST /albums.json
  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render action: 'show', status: :created, location: @album }
      else
        format.html { render action: 'new' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:name, :description)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.haml
= simple_form_for(@album) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :description

  .form-actions
    = f.button :submit

app/views/albums/edit.html.haml
%h1 Editing album

= render 'form'

= link_to 'Show', @album
\|
= link_to 'Back', albums_path

app/views/albums/index.html.haml
%h1 Albums

%table
  - @albums.each do |album|
    %tr
      %h2= link_to album.name, album
      %h3= album.description
      %p
        - album.photos.each do |photo|
          = link_to image_tag(photo.photo_path, size: "270x180"), album_photo_path(album, photo.id)
      -#  - for i in 1..3 
      -#    = link_to image_tag(album.photos[i].photo_path, size: "270x180"), album.photos[i].photo_path
      = link_to 'Show', album
      \|
      = link_to 'Photos', album_photos_path(album)
      \|
      = link_to 'New Photo', new_album_photo_path(album)
      \|
      = link_to 'Edit', edit_album_path(album)
      \|
      = link_to 'Destroy', album, :method => :delete, :data => { :confirm => 'Are you sure?' }


= link_to 'New Album', new_album_path

%br

app/views/albums/new.html.haml
%h1 New album

= render 'form'

= link_to 'Back', albums_path

app/views/albums/show.html.haml
%p#notice= notice

%p
  %h2= @album.name
%p
  %h3= @album.description
%p
  - @album.photos.each do |photo|
    %div{:style => "float: left; padding-left: 15px; padding-bottom: 15px;"}
      .lightbox_content
        = link_to image_tag(photo.photo_path, size: "540x360"), photo.photo_path
      -#= link_to #image_tag(photo.photo_path, size: "45x30"), 
      -#:"data-lightbox" => ".lightbox_content"
      -#= image_tag(photo.photo_path, size: "45x30") 
%div{:style => "clear: both;"}
= link_to 'Edit', edit_album_path(@album)
\|
= link_to 'Photos', album_photos_path(@album)
\|
= link_to 'New Photo', new_album_photo_path(@album)
\|
= link_to 'Destroy', @album, :method => :delete, :data => { :confirm => 'Are you sure?' }
\|
= link_to 'New Album', new_album_path
\|
= link_to 'Back', albums_path