config/routes.rb
Myapp::Application.routes.draw do
  resources :pi_settings

  resources :albums do
    resources :photos
  end

  root :to => 'visitors#new'
end

app/models/pi_setting.rb
class PiSetting < ActiveRecord::Base
end

app/controllers/pi_settings_controller.rb
class PiSettingsController < ApplicationController
  before_action :set_pi_setting, only: [:show, :edit, :update, :destroy]

  # GET /pi_settings
  # GET /pi_settings.json
  def index
    @pi_settings = PiSetting.all
  end

  # GET /pi_settings/1
  # GET /pi_settings/1.json
  def show
  end

  # GET /pi_settings/new
  def new
    @pi_setting = PiSetting.new
  end

  # GET /pi_settings/1/edit
  def edit
  end

  # POST /pi_settings
  # POST /pi_settings.json
  def create
    @pi_setting = PiSetting.new(pi_setting_params)

    respond_to do |format|
      if @pi_setting.save
        format.html { redirect_to @pi_setting, notice: 'Pi setting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @pi_setting }
      else
        format.html { render action: 'new' }
        format.json { render json: @pi_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pi_settings/1
  # PATCH/PUT /pi_settings/1.json
  def update
    respond_to do |format|
      if @pi_setting.update(pi_setting_params)
        format.html { redirect_to @pi_setting, notice: 'Pi setting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @pi_setting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pi_settings/1
  # DELETE /pi_settings/1.json
  def destroy
    @pi_setting.destroy
    respond_to do |format|
      format.html { redirect_to pi_settings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pi_setting
      @pi_setting = PiSetting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pi_setting_params
      params.require(:pi_setting).permit(:display, :capture, :album)
    end
end

app/helpers/pi_settings_helper.rb
module PiSettingsHelper
end

app/views/pi_settings/_form.html.haml
= simple_form_for(@pi_setting) do |f|
  = f.error_notification

  .form-inputs
    = f.input :display
    = f.input :capture
    = f.input :album

  .form-actions
    = f.button :submit

app/views/pi_settings/edit.html.haml
%h1 Editing pi_setting

= render 'form'

= link_to 'Show', @pi_setting
\|
= link_to 'Back', pi_settings_path

app/views/pi_settings/index.html.haml
%h1 Pi Settings
- @pi_settings.each do |pi_setting|
  %h3= pi_setting.display ? "Display On" : "Display Off"
  %h3= pi_setting.capture ? "Capture On" : "Capture Off"
  = link_to 'Edit', edit_pi_setting_path(pi_setting)

%br

-#= link_to 'New Pi setting', new_pi_setting_path

app/views/pi_settings/new.html.haml
%h1 New pi_setting

= render 'form'

= link_to 'Back', pi_settings_path

app/views/pi_settings/show.html.haml
%p#notice= notice
%h1 Pi Settings
%p
  %h3= @pi_setting.display ? "Display On" : "Display Off"
  %h3= @pi_setting.capture ? "Capture On" : "Capture Off"
%p
  -#%h3 Album:
  -#%h3= @pi_setting.album

= link_to 'Edit', edit_pi_setting_path(@pi_setting)
\|
= link_to 'Back', pi_settings_path