config/routes.rb
Myapp::Application.routes.draw do
  resources :pi_settings

  resources :albums do
    resources :photos
  end

  root :to => 'visitors#new'
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  #validates_presence_of :photo_file #add other mandatory attrs here...
  after_save :store_photo
  belongs_to :album

  def photo_file=(file_data)
    unless file_data.blank?
      #store uploaded data in a private instance var
      @file_data = file_data
      #set title to be unique file name
      logger.debug("self.title is... #{self.title}")
    end
  end

  PHOTO_STORE = File.join(Rails.root, 'public', 'photo_store')

# write image file here
  def photo_filename
    File.join(PHOTO_STORE, "/#{self.title}_#{self.created_at}.jpg")
    #File.join(PHOTO_STORE, "/#{self.title}")
  end
 
  #def make_file
   # File.open("/Users/graceschuurmans/firstSite/myapp/public/test.txt", "w") { |f| f.write("I did it!") }
  #end

# return a path to photo to use in the view
  def photo_path
    "/photo_store/#{self.title}_#{self.created_at}.jpg"
  end

  def delete_photo
    if File.exist?(photo_filename)
      File.delete(photo_filename) 
    else
      logger.info "photo not present- cannot delete"
    end
  end

  private

  def store_photo
    if @file_data 
      logger.debug("got inside store_photo this time")
      #make photo store directory if doesn't already exist
      FileUtils.mkdir_p PHOTO_STORE

      self.timestamp = self.created_at
      logger.debug("self timestamp is... #{self.timestamp}")

      #write photo data to file
      logger.debug("photo filename: #{photo_filename}")
      begin
        file_content = Base64.decode64(@file_data) #try to decode, will write bytes if not base64
      rescue
        File.open(photo_filename, 'wb') do |f| 
          f.write(@file_data.read)
        end
      else
        File.open(photo_filename, 'wb') do |f| #write base64 decoded if from Pi
          f.write(file_content)
        end
      end
      #file only saves when it newly arrives to model being saved
      @file_data = nil
    else
      logger.debug("NO FILE DATA in store_photo")
    end
  end

end

app/controllers/photos_controller.rb
require 'debugger'

class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_filter :get_album
  
  # GET /photos
  # GET /photos.json
  def index
    @photos = @album.photos
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
   @photo = @album.photos.find(params[:id])  
  end

  # GET /photos/new
  def new
    @photo = Photo.new(album_id: @album.id)
  end

  # GET /photos/1/edit
  def edit
    @photo = @album.photos.find(params[:id])  
  end

  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    respond_to do |format|
      if @photo.save
        format.html { redirect_to album_photos_url(@album), notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def photo_file
    @photo = Photo.new(photo_params)
    @photo.photo_path
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to album_photos_url(@album), notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    logger.debug("deleting #{@photo.photo_filename}")
    @photo.delete_photo 
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to album_photos_url(@album) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:title, :timestamp, :photo_file, :description, :album_id)
    end

    # converts the album_id from routing to an @album object to use in the view
    def get_album
      @album = Album.find(params[:album_id])
    end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_form.html.haml
= simple_form_for([@album, @photo], :html => {:multipart => true}) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :timestamp
    = f.input :description
    -#= f.select :album_id, Album.find(:all).collect {|a| [a.name, a.id]}
    = f.select :album_id, Album.all.collect {|a| [a.name, a.id]}
  .form-fields
    = f.file_field :photo_file
  .form-actions
    = f.button :submit
  

app/views/photos/edit.html.haml
%h1 Editing photo

= render 'form'

= link_to 'Show', album_photo_path
\|
= link_to 'Back', album_photos_path

app/views/photos/index.html.haml
%h1 Listing photos

%table
  %tr
    %th Title
    %th Timestamp
    %th Photo File 
    %th Description
    %th Album ID
    %th
    %th

  - @photos.each do |photo|
    %tr
      %td= photo.title
      %td= photo.timestamp
      %td= link_to image_tag(photo.photo_path, size: "540x360"), photo.photo_path
      %td= photo.description
      %td= photo.album_id
      %td= link_to 'Show', album_photo_path(@album, photo.id)
      %td= link_to 'Edit', edit_album_photo_path(@album, photo.id)
      %td= link_to 'Destroy', album_photo_path(@album, photo.id), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Photo', new_album_photo_path

app/views/photos/new.html.haml
%h1 New photo

= render 'form'

= link_to 'Back', new_album_photo_path

app/views/photos/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @photo.title
%p
  %b Timestamp:
  = @photo.timestamp
%p
  %b In Album:
  = link_to @photo.album.name #@photo.photo_file
  -#= @photo.album_id
%p
  %b Description:
  = @photo.description
%p
  %b Photo:
  = image_tag @photo.photo_path
= link_to 'Edit', edit_album_photo_path(@album, @photo)
\|
= link_to 'Back', album_photos_path
\|
= link_to 'Albums', albums_path